import re

filepath = r'c:\Users\cesar\OneDrive\Área de Trabalho\sitephc_br\product\31\index.html'
with open(filepath, 'r', encoding='utf-8') as f:
    html = f.read()

replacements = {
    r">About Us<": ">Sobre Nós<",
    r">News<": ">Notícias<",
    r">INNOVATIONS<": ">INOVAÇÕES<",
    r">Products<": ">Produtos<",
    r">Check code<": ">Verificar código<",
    r">Dealers<": ">Revendedores<",
    r">Analysis<": ">Análises<",
    r">Contact<": ">Contato<",
    r\">Premium Line<\": \">Linha Premium<\",
    r\">Orals<\": \">Orais<\",
    r\">HGH and Peptides<\": \">HGH e Peptídeos<\",
    r\">Injectables<\": \">Injetáveis<\",
    r">Post-cycle therapy \(PCT\)<": ">Terapia Pós-ciclo (TPC)<",
    r">Fat loss<": ">Perda de gordura<",
    r">Basic Line<": ">Linha Básica<",
    r">Testosterones<": ">Testosteronas<",
    r">Nandrolones<": ">Nandrolonas<",
    r">Boldenones<": ">Boldenonas<",
    r">Trenbolones<": ">Trembolonas<",
    r">Stanozolol<": ">Estanozolol<",
    r">Primobolan<": ">Primobolan<",
    r">Masterones<": ">Masteronas<",
    r">Mixes Special Line<": ">Linha Especial de Misturas<",
    r">Methandienone inj\.<": ">Metandienona injetável<",
    r">Oxymetholone inj\.<": ">Oximetolona injetável<",
    r"Products // Orals // DIANABOLOS": "Produtos // Orais // DIANABOLOS",
    r"10 mg / pill": "10 mg / comprimido",
    r">Methandienone<": ">Metandienona<",
    r"Methandienone \(also known as Dianabol and methandrostenolone\) was the first orally active anabolic steroid to be synthesized and sold on the prescription market and is historically considered to be the most popular performance enhancing drug ever used in strength and physique sports\. Methandienone is a C17-alpha-alkylated orally effective anabolic steroid that was released by Ciba Pharmaceuticals to the U\.S\. prescription drug market in 1958 under the famous brand name Dianabol\. Ciba developed methandrostenolone into a medicine with the help of Dr\. John Ziegler, who was the team physician for a number of U\.S\. Olympic teams, including weightlifting\.": "A Metandienona (também conhecida como Dianabol e metandrostenolona) foi o primeiro esteroide anabolizante oralmente ativo a ser sintetizado e vendido sob prescrição, e é historicamente designada como a droga de aprimoramento de desempenho mais popular já usada em esportes de força e fisiculturismo. A Metandienona é um esteroide anabolizante oralmente eficaz, alquilado em C17-alfa, que foi lançado pela Ciba Pharmaceuticals nos Estados Unidos em 1958 sob a famosa marca Dianabol. A Ciba desenvolveu a metandrostenolona para uso médico com a ajuda do Dr. John Ziegler, que era médico de várias equipes olímpicas dos EUA, incluindo a de levantamento de peso.",
    r"Methandienone affects metabolism and cellular physiology very significantly, resulting in dramatic increases in protein synthesis, glycogenolysis, and muscle strength in a relatively short period of time\. The C17-alpha-alkylation makes methandienone more resistant to hepatic breakdown, which allows it to be administered orally and still have a notably strong effect\. As a result, it may exert stress on the liver\. In summary, methandienone has earned an outstanding reputation as a potent tool for making quick gains or retaining gains and is widely recognized as a very good drug when used properly and safely\.": "A Metandienona afeta o metabolismo e a fisiologia celular de forma muito significativa, resultando em um aumento considerável na síntese de proteínas, na glicogenólise e na força muscular em um período de tempo relativamente curto. A alquilação C17-alfa torna a metandienona mais resistente à degradação hepática, o que permite sua administração por via oral acompanhada de efeitos notavelmente fortes. Como resultado, ela pode exercer estresse sobre o fígado. Em resumo, a metandienona ganhou uma excelente reputação como uma ferramenta potente para a obtenção de ganhos rápidos de massa muscular e retenção. Ela é amplamente reconhecida como uma droga excepcional quando usada de forma adequada e segura.",
    r"WARNING: Methandienone easily aromatizes into methylestradiol, which is up to 30% more active compared to regular estradiol\. Accordingly, getting blood work to evaluate individual responses and the use of aromatase inhibitors are recommended when taking methandienone\. Due to its C17-alpha-alkylation, methandienone may exert stress on the liver\. Therefore, healthy lifestyle choices and the use of supplements to promote liver health are advisable\. The recommended methandienone cycle duration should be no longer than 6 8 weeks\.": "AVISO: A Metandienona aromatiza-se facilmente em metilestradiol, hormônio que possui até 30% mais atividade em comparação com o estradiol normal. Consequentemente, recomendamos avaliações com base em exames de sangue a fim de documentarmos as respostas únicas de cada indivíduo bem como o uso de inibidores de aromatase para quem realiza a ingestão de metandienona. Devido à sua alquilação C17-alfa, a metandienona pode causar estresse no fígado. Portanto, manter escolhas de estilo de vida saudáveis e utilizar suplementação de forma a auxiliar e promover a saúde hepática são procedimentos estritamente aconselháveis. A duração recomendada de um ciclo de metandienona não deve exceder um limite temporal delimitado de 6 a 8 semanas.",
    r">Chemical name <": ">Nome químico <",
    r">Formula <": ">Fórmula <",
    r">Anabolic activity index <": ">Índice de atividade anabólica <",
    r">Androgenic activity index <": ">Índice de atividade androgênica <",
    r">Active half-life\s*<": ">Meia-vida ativa<",
    r">Classification\s*<": ">Classificação<",
    r">Dosage\s*<": ">Dosagem<",
    r">Acne\s*<": ">Acne<",
    r">4-6 hours\s*<": ">4-6 horas<",
    r">Anabolic steroid\s*<": ">Esteroide anabolizante<",
    r">Men 20-50 mg/day\s*<": ">Homens 20-50 mg/dia<",
    r">Yes\s*<": ">Sim<",
    r">WATER RETENTION\s*<": ">RETENÇÃO DE LÍQUIDOS<",
    r">Hepatoxity\s*<": ">Hepatotoxicidade<",
    r">Aromatization\s*<": ">Aromatização<",
    r">High\s*<": ">Alta<",
    r"WE RECOMMEND TO USE IN STACK WITH THIS PRODUCT THE FOLLOWING ITEMS:": "RECOMENDAMOS USAR EM COMBINAÇÃO COM ESTE PRODUTO OS SEGUINTES ITENS:",
    r">Muscle Mass<": ">Massa Muscular<",
    r">Burning<": ">Queima<",
    r">Recovery<": ">Recuperação<",
    r">TESTOSTERONES<": ">TESTOSTERONAS<",
    r">NANDROLONES<": ">NANDROLONAS<",
    r">TRENBOLONES<": ">TREMBOLONAS<",
    r">BOLDENONES<": ">BOLDENONAS<",
    r">STANOZOLOL<": ">ESTANOZOLOL<",
    r">MASTERONES<": ">MASTERONAS<",
    r">MIXES \(SPECIAL LINE\)<": ">MISTURAS (LINHA ESPECIAL)<",
    r">ORAL PRODUCTS<": ">PRODUTOS ORAIS<",
    r">PRIMOBOLONES<": ">PRIMOBOLAN<",
    r">Nandrolone Phenylpropionate<": ">Fenilpropionato de Nandrolona<",
    r">Boldenone Undecylenate<": ">Undecilenato de Boldenona<",
    r">Trenbolone Acetate<": ">Acetato de Trembolona<",
    r">Trenbolone Enanthate<": ">Enantato de Trembolona<",
    r">trenbolone hexahydrobenzylcarbonate<": ">Hexahidrobenzilcarbonato de trembolona<",
    r">Methanolon Enanthate<": ">Enantato de Metenolona<",
    r">Test\. Phenyl\.; Test\. Cyp\.; Bold\. Undecyl\.<": ">Fenil. de Test.; Cip. de Test.; Undecil. de Bold.<",
    r">Tren\. Ace; Drost\. Prop; Test\. Phenyl<": ">Acet. de Trem.; Prop. de Drost.; Fenil. de Test.<",
    r">Test\. Enanth;Nandr\. Deca;Tren Enanth\.<": ">Enant. de Test.; Deca. de Nandr.; Enant. de Trem.<",
    r">Oxymetholone<": ">Oximetolona<",
    r">Nand\. Phenyl; Nand\. Deca; Test\. Phenyl; Test\. Deca<": ">Fenil. de Nand.; Deca. de Nand.; Fenil. de Test.; Deca. de Test.<",
    r">Test Enant\.; Tren Enant\.; Drost\. Enant\.<": ">Enant. de Test.; Enant. de Trem.; Enant. de Drost.<",
    r">Testosterone Propionate<": ">Propionato de Testosterona<",
    r">Testosterone Phenylpropionate<": ">Fenilpropionato de Testosterona<",
    r">Testosterone Enanthate<": ">Enantato de Testosterona<",
    r">Testosterone Cypionate<": ">Cipionato de Testosterona<",
    r">Blend of 4 Testosterone esters<": ">Mistura de 4 ésteres de Testosterona<",
    r">Nandrolone Decanoate<": ">Decanoato de Nandrolona<",
    r">Blend of 2 Nandrolones<": ">Mistura de 2 Nandrolonas<",
    r">Blend of 3 Trenbolones<": ">Mistura de 3 Trembolonas<",
    r">Blend of Drostanolone esters<": ">Mistura de ésteres de Drostanolona<",
    r"Ampules": "Ampolas",
    r">Blend of 4 Testosterones<": ">Mistura de 4 Testosteronas<",
    r">Blend of 4 Nandrolones<": ">Mistura de 4 Nandrolonas<",
    r">Blend of Drostanolones<": ">Mistura de Drostanolonas<",
    r">Chlorodehydromethyteststerone<": ">Clorodesidrometiltestosterona<",
    r">Oxandrolone<": ">Oxandrolona<",
    r">Mesterolone<": ">Mesterolona<",
    r">Fluoxymesterone<": ">Fluoximesterona<",
    r">Anastrozole<": ">Anastrozol<",
    r">Testosterone Base<": ">Testosterona Base<",
    r">Human Growth Hormone<": ">Hormônio do Crescimento Humano<",
    r">Isotretinoin<": ">Isotretinoína<",
    r">Toremifene citrate<": ">Citrato de toremifeno<",
    r">Clomiphene citrate<": ">Citrato de clomifeno<",
    r">Exemestane<": ">Exemestano<",
    r">Letrozol<": ">Letrozol<",
    r">Cabergoline<": ">Cabergolina<",
    r">Trenbolone base<": ">Trembolona base<",
    r">Testosterone Undecanoate<": ">Undecanoato de Testosterona<",
    r">Methyldrostanolone<": ">Metildrostanolona<",
    r"&nbsp;": " "
}

for k, v in replacements.items():
    html = re.sub(k, v, html)

# Clean up some artifacts
html = html.replace('.\xef\xbf\xbd', '.')
html = html.replace('\xef\xbf\xbd', '')
html = html.replace('', '')

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(html)
